version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ../src:/var/www/html
    ports:
      - 8181:80
    depends_on:
      - db
    networks:
      - laravel5

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: laravel5
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel5
      MYSQL_PASSWORD: secret
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - laravel5
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
     - 8081:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    depends_on:
      - db
    networks:
     - laravel5

volumes:
  dbdata:

networks:
  laravel5:
    driver: bridge
  